name: cloud_media
description: Cloud Media
publish_to: none

dependencies:
  audioplayers: ^1.0.1
  flutter:
    sdk: flutter
  http: ^0.13.1
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  provider: 5.0.0
  get: any
  dio: any
  get_storage: any
  lottie: ^1.4.0
  collection: ^1.16.0
  connectivity_plus: ^2.3.6
  

dev_dependencies:
  flame_lint: 0.1.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"
